In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("D:\ipl_matches.csv")

# EXPLORATORY DATA ANALYSIS

In [3]:
df.head()

id  season       city        date                        team1  \
0   1    2017  Hyderabad  2017-04-05          Sunrisers Hyderabad   
1   2    2017       Pune  2017-04-06               Mumbai Indians   
2   3    2017     Rajkot  2017-04-07                Gujarat Lions   
3   4    2017     Indore  2017-04-08       Rising Pune Supergiant   
4   5    2017  Bangalore  2017-04-08  Royal Challengers Bangalore   

                         team2                  toss_winner toss_decision  \
0  Royal Challengers Bangalore  Royal Challengers Bangalore         field   
1       Rising Pune Supergiant       Rising Pune Supergiant         field   
2        Kolkata Knight Riders        Kolkata Knight Riders         field   
3              Kings XI Punjab              Kings XI Punjab         field   
4             Delhi Daredevils  Royal Challengers Bangalore           bat   

   result  dl_applied                       winner  win_by_runs  \
0  normal           0          Sunrisers Hyderabad           35   
1  normal           0       Rising Pune Supergiant            0   
2  normal           0        Kolkata Knight Riders            0   
3  normal           0              Kings XI Punjab            0   
4  normal           0  Royal Challengers Bangalore           15   

   win_by_wickets player_of_match                                      venue  \
0               0    Yuvraj Singh  Rajiv Gandhi International Stadium, Uppal   
1               7       SPD Smith    Maharashtra Cricket Association Stadium   
2              10         CA Lynn     Saurashtra Cricket Association Stadium   
3               6      GJ Maxwell                     Holkar Cricket Stadium   
4               0       KM Jadhav                      M Chinnaswamy Stadium   

          umpire1        umpire2  umpire3  
0     AY Dandekar       NJ Llong      NaN  
1  A Nand Kishore         S Ravi      NaN  
2     Nitin Menon      CK Nandan      NaN  
3    AK Chaudhary  C Shamshuddin      NaN  
4             NaN            NaN      NaN

In [4]:
df.columns

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [5]:
df.team1.unique()

array(['Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Royal Challengers Bangalore',
       'Kolkata Knight Riders', 'Delhi Daredevils', 'Kings XI Punjab',
       'Chennai Super Kings', 'Rajasthan Royals', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants'],
      dtype=object)

### FEATUR ENGINEERING

In [6]:
df.groupby('winner')['winner'].agg('count')

winner
Chennai Super Kings            79
Deccan Chargers                29
Delhi Daredevils               62
Gujarat Lions                  13
Kings XI Punjab                70
Kochi Tuskers Kerala            6
Kolkata Knight Riders          77
Mumbai Indians                 92
Pune Warriors                  12
Rajasthan Royals               63
Rising Pune Supergiant         10
Rising Pune Supergiants         5
Royal Challengers Bangalore    73
Sunrisers Hyderabad            42
Name: winner, dtype: int64

In [7]:
df.groupby('winner')['winner'].agg('count').sum()

633

In [8]:
import matplotlib.pyplot as plt

In [9]:
df.columns

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [10]:
df.team1.unique()

array(['Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Royal Challengers Bangalore',
       'Kolkata Knight Riders', 'Delhi Daredevils', 'Kings XI Punjab',
       'Chennai Super Kings', 'Rajasthan Royals', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants'],
      dtype=object)

### Considering the present teams

In [11]:
final_teams=['Sunrisers Hyderabad', 'Mumbai Indians',
        'Royal Challengers Bangalore',
       'Kolkata Knight Riders', 'Delhi Daredevils', 'Kings XI Punjab',
       'Chennai Super Kings', 'Rajasthan Royals']

In [12]:
df=df[(df['team1'].isin(final_teams)) & (df['team2'].isin(final_teams))]

In [13]:
df.team1.unique()

array(['Sunrisers Hyderabad', 'Royal Challengers Bangalore',
       'Kolkata Knight Riders', 'Kings XI Punjab', 'Delhi Daredevils',
       'Mumbai Indians', 'Chennai Super Kings', 'Rajasthan Royals'],
      dtype=object)

In [14]:
df.city.unique()

array(['Hyderabad', 'Bangalore', 'Mumbai', 'Indore', 'Kolkata', 'Delhi',
       'Chandigarh', 'Jaipur', 'Chennai', 'Cape Town', 'Port Elizabeth',
       'Durban', 'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Dharamsala', 'Pune', 'Raipur',
       'Ranchi', 'Abu Dhabi', 'Sharjah', nan, 'Cuttack', 'Visakhapatnam'],
      dtype=object)

In [15]:
df[df.city.values=='East London']

id  season         city        date           team1  \
137  138    2009  East London  2009-05-01  Mumbai Indians   
149  150    2009  East London  2009-05-08  Mumbai Indians   

                     team2     toss_winner toss_decision  result  dl_applied  \
137  Kolkata Knight Riders  Mumbai Indians           bat  normal           0   
149       Delhi Daredevils  Mumbai Indians           bat  normal           0   

               winner  win_by_runs  win_by_wickets player_of_match  \
137    Mumbai Indians            9               0       JP Duminy   
149  Delhi Daredevils            0               7         A Nehra   

            venue    umpire1      umpire2  umpire3  
137  Buffalo Park  M Erasmus  SK Tarapore      NaN  
149  Buffalo Park  M Erasmus  SK Tarapore      NaN

In [16]:
df.groupby('venue')['venue'].agg('count')

venue
Barabati Stadium                                         3
Brabourne Stadium                                       10
Buffalo Park                                             2
De Beers Diamond Oval                                    1
Dr DY Patil Sports Academy                               5
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium      6
Dubai International Cricket Stadium                      7
Eden Gardens                                            52
Feroz Shah Kotla                                        48
Himachal Pradesh Cricket Association Stadium             7
Holkar Cricket Stadium                                   2
JSCA International Stadium Complex                       6
Kingsmead                                               12
M Chinnaswamy Stadium                                   54
MA Chidambaram Stadium, Chepauk                         40
Maharashtra Cricket Association Stadium                  4
New Wanderers Stadium                             

In [17]:
df.columns

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [18]:
columns_req=['season', 'city',  'team1', 'team2','toss_winner', 
       'toss_decision',  'winner']

In [19]:
df1=df[columns_req]

In [20]:
df1.head()

season       city                        team1  \
0    2017  Hyderabad          Sunrisers Hyderabad   
4    2017  Bangalore  Royal Challengers Bangalore   
6    2017     Mumbai        Kolkata Knight Riders   
7    2017     Indore  Royal Challengers Bangalore   
9    2017     Mumbai          Sunrisers Hyderabad   

                         team2                  toss_winner toss_decision  \
0  Royal Challengers Bangalore  Royal Challengers Bangalore         field   
4             Delhi Daredevils  Royal Challengers Bangalore           bat   
6               Mumbai Indians               Mumbai Indians         field   
7              Kings XI Punjab  Royal Challengers Bangalore           bat   
9               Mumbai Indians               Mumbai Indians         field   

                        winner  
0          Sunrisers Hyderabad  
4  Royal Challengers Bangalore  
6               Mumbai Indians  
7              Kings XI Punjab  
9               Mumbai Indians

In [21]:
df1.isna().sum()

season           0
city             7
team1            0
team2            0
toss_winner      0
toss_decision    0
winner           2
dtype: int64

In [22]:
df1=df1.dropna(axis=0)

In [23]:
df1.isna().sum()

season           0
city             0
team1            0
team2            0
toss_winner      0
toss_decision    0
winner           0
dtype: int64

In [24]:
type(df1['season'].values[1])

numpy.int64

In [25]:
df1.replace(['Mumbai Indians','Kolkata Knight Riders','Royal Challengers Bangalore','Chennai Super Kings',
                 'Rajasthan Royals','Delhi Daredevils','Kings XI Punjab',
                 'Sunrisers Hyderabad']
                ,['MI','KKR','RCB','CSK','RR','DD','KXIP','SRH'],inplace=True
        )

In [26]:
encode = {'team1': {'MI':1,'KKR':2,'RCB':3,'CSK':4,'RR':5,'DD':6,'KXIP':7,'SRH':8},
          'team2': {'MI':1,'KKR':2,'RCB':3,'CSK':4,'RR':5,'DD':6,'KXIP':7,'SRH':8},
          'toss_winner': {'MI':1,'KKR':2,'RCB':3,'CSK':4,'RR':5,'DD':6,'KXIP':7,'SRH':8},
          'winner': {'MI':1,'KKR':2,'RCB':3,'CSK':4,'RR':5,'DD':6,'KXIP':7,'SRH':8,'Draw':9}}

In [27]:
df1.replace(encode,inplace=True)

In [28]:
df1.head()

season       city  team1  team2  toss_winner toss_decision  winner
0    2017  Hyderabad      8      3            3         field       8
4    2017  Bangalore      3      6            3           bat       3
6    2017     Mumbai      2      1            1         field       1
7    2017     Indore      3      7            3           bat       7
9    2017     Mumbai      8      1            1         field       1

In [29]:
df1.toss_decision=df1.toss_decision.apply(lambda x: 0 if x=='field' else 1)

In [30]:
df1.head()

season       city  team1  team2  toss_winner  toss_decision  winner
0    2017  Hyderabad      8      3            3              0       8
4    2017  Bangalore      3      6            3              1       3
6    2017     Mumbai      2      1            1              0       1
7    2017     Indore      3      7            3              1       7
9    2017     Mumbai      8      1            1              0       1

In [31]:
df1.city.unique()

array(['Hyderabad', 'Bangalore', 'Mumbai', 'Indore', 'Kolkata', 'Delhi',
       'Chandigarh', 'Jaipur', 'Chennai', 'Cape Town', 'Port Elizabeth',
       'Durban', 'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Dharamsala', 'Pune', 'Raipur',
       'Ranchi', 'Abu Dhabi', 'Sharjah', 'Cuttack', 'Visakhapatnam'],
      dtype=object)

In [32]:
df1.city.replace(['Hyderabad', 'Bangalore', 'Mumbai', 'Indore', 'Kolkata', 'Delhi',
       'Chandigarh', 'Jaipur', 'Chennai', 'Cape Town', 'Port Elizabeth',
       'Durban', 'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Dharamsala', 'Pune', 'Raipur',
       'Ranchi', 'Abu Dhabi', 'Sharjah', 'Cuttack', 'Visakhapatnam'],['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26'],inplace=True)

In [33]:
df1.head()

season city  team1  team2  toss_winner  toss_decision  winner
0    2017    1      8      3            3              0       8
4    2017    2      3      6            3              1       3
6    2017    3      2      1            1              0       1
7    2017    4      3      7            3              1       7
9    2017    3      8      1            1              0       1

In [34]:
df1.season.unique()

array([2017, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016],
      dtype=int64)

In [35]:
df1[df1.season<=2014]

season city  team1  team2  toss_winner  toss_decision  winner
59     2008    2      2      3            3              0       2
60     2008    7      4      7            4              1       4
61     2008    6      5      6            5              1       6
62     2008    3      1      3            1              1       3
64     2008    8      7      5            7              1       5
..      ...  ...    ...    ...          ...            ...     ...
512    2014    3      5      1            1              0       1
513    2014    5      2      7            7              0       2
514    2014    3      1      4            4              0       4
515    2014    3      7      4            4              0       7
516    2014    2      7      2            2              0       2

[322 rows x 7 columns]

In [36]:
df1.shape

(442, 7)

In [37]:
x=df1.drop('winner',axis=1)

In [38]:
y=df1.winner

In [39]:
from sklearn.tree import DecisionTreeClassifier

In [40]:
from sklearn.ensemble import RandomForestClassifier 

In [41]:
from sklearn.linear_model import LogisticRegression

In [42]:
from sklearn.svm import SVC

In [43]:
from sklearn.model_selection import GridSearchCV 

In [44]:
model_params={
  
         
    
'randomforest':{
                    'model':RandomForestClassifier(criterion='gini'),
                    'params':{
                        'n_estimators':[1,5]
                    }
              },
    
    
'logistic regression':{
                          'model':LogisticRegression(),
                          'params':{'C' : [1,5]}
                     }
}



In [45]:
scores=[]

In [46]:
for model_name, mp in model_params.items():
    Clf= GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    Clf.fit(x,y)
    scores.append({
                 'model':model_name,
                  'best_score': Clf.best_score_,
                'best_params': Clf.best_params_
                 
    })

D:\anaconda_app\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\anaconda_app\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimiz

In [47]:
df_=pd.DataFrame(scores,columns=['model','best_score', 'best_params'])

In [48]:
df_

model  best_score          best_params
0         randomforest    0.454801  {'n_estimators': 5}
1  logistic regression    0.287257             {'C': 1}

In [49]:
model=SVC()

In [50]:
model.fit(x,y)

SVC()

In [51]:
model.score(x,y)

0.17420814479638008

In [52]:
model=RandomForestClassifier()

In [53]:
model.fit(x,y)

RandomForestClassifier()

In [54]:
final_model=model.score(x,y)

In [55]:
final_model

0.9932126696832579

### Prediction

In [56]:
df1.head()

season city  team1  team2  toss_winner  toss_decision  winner
0    2017    1      8      3            3              0       8
4    2017    2      3      6            3              1       3
6    2017    3      2      1            1              0       1
7    2017    4      3      7            3              1       7
9    2017    3      8      1            1              0       1

In [57]:
     dicVal = encode['winner']


In [58]:
team1='SRH'
team2='RCB'
toss_winner='RCB'

In [59]:
input=[2017,1,dicVal[team1],dicVal[team2],3,0]

In [60]:
import numpy as np

In [61]:
input = np.array(input).reshape((1, -1))

In [62]:
model.predict(input)

array([8], dtype=int64)

In [63]:
team1='KKR'
team2='RCB'
toss_winner='KKR'

In [64]:
input=[2017,2,dicVal[team1],dicVal[team2],2,0]

In [65]:
input = np.array(input).reshape((1, -1))

In [66]:
model.predict(input)

array([2], dtype=int64)

In [67]:
team1='KKR'
team2='RCB'
toss_winner='RCB'

In [68]:
input=[2020,2,dicVal[team1],dicVal[team2],3,0]

In [69]:
input = np.array(input).reshape((1, -1))

In [70]:
model.predict(input)

array([3], dtype=int64)

In [71]:
import pickle

In [72]:
filename = 'finalized_model.sav'
pickle.dump(model, open(filename, 'wb'))